name: Scan with Trivy and upload results to GitHub Security tab
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  scan-vulnerabilities:
    name: Scan for vulnerabilities with Trivy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          scan-ref: .
          format: json
          output: trivy-report.json
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Upload artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.json
